### ISSUE TITLE
关于Stream的疑问

### ISSUE THREAD

**Issue by trainges** [hugojing/toolbox-weex#1]
你好,我用了你的代码去跑,无论是在浏览器上还是PlayGroup里面,Stream调用有道的Http的Api都不成功,请问要怎么处理?

**Comment by hugojing** [comment]
你好，请详细说一下错误信息。

一般来说，如果是我的代码，并且已安装依赖，调用有道的 **https** API 都是可以成功的。

如果仅仅是调用 API 不成功，有可能是因为 **每个 API key 请求频率限制为每小时1000次，超过限制会被封禁。** （这里用的是我的 key）

但是测试了一下并没有被禁：https://fanyi.youdao.com/openapi.do?keyfrom=min-toolbox&key=1267180728&type=data&doctype=json&version=1.1&q=上海

还得看你的具体错误信息才能判定原因。

**Comment by trainges** [comment]
我是直接
1.weex translate.we
浏览器上就是报:
XMLHttpRequest cannot load https://fanyi.youdao.com/openapi.do?keyfrom=min-toolbox&key=1267180728&type=data&doctype=json&version=1.1&q=翻译. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://127.0.0.1:8081' is therefore not allowed access.

2.weex translate.we --qr 手机扫描二维码之后,访问也不行.
Stream.fetch回调函数的status为-1

还有另外一个疑问,
weex translate.we --qr,你的Modal 模块的 alert 的写法,在PlayGround中没有办法弹出来.我用的是ios版本的PlayGround.我用他Example中的写法就可以显示

**Comment by hugojing** [comment]
1 是因为浏览器的跨域限制，用一些 CORS Toggle 之类的浏览器插件可以越过限制。

2 这个就不清楚了。官方文档标准写法（ http://alibaba.github.io/weex/doc/modules/modal.html ），在我这边没问题。

**Comment by trainges** [comment]
你好,在浏览器上安装 CORS Toggle .手机跟浏览器都可以访问了.  能不能解释一下,为什么在浏览器上安装 CORS Toggle ,PlayGround就可以访问有道的api了.这个不太能理解.

**Comment by hugojing** [comment]
浏览器是因为有跨域限制，具体你可以自己搜索一下。

至于 playground 为什么可以，我不清楚，这个跟浏览器应该是没关系的。
