### ISSUE TITLE
运行不起来求大神解答一下

### ISSUE THREAD

**Issue by wangGuangXu** [hugojing/toolbox-weex#10]
运行的时候报这个错：
E:\weexs\toolbox-weex-master\src>weex main.we --qr
ERR! ModuleBuildError: Module build failed: ReferenceError: Unknown plugin "C:\
Users\Administrator\AppData\Roaming\npm\node_modules\weex-toolkit\node_mo
dules\weex-loader\node_modules\babel-plugin-transform-runtime" specified in "
base" at 0, attempted to resolve relative to "E:\weexs\toolbox-weex-master\sr
c"
    at C:\Users\Administrator\AppData\Roaming\npm\node_modules\weex-toolkit\node
_modules\babel-core\lib\transformation\file\options\option-manager.js:172:17
    at Array.map (native)
    at Function.normalisePlugins (C:\Users\Administrator\AppData\Roaming\npm\nod
e_modules\weex-toolkit\node_modules\babel-core\lib\transformation\file\options\o
ption-manager.js:150:20)
    at OptionManager.mergeOptions (C:\Users\Administrator\AppData\Roaming\npm\no
de_modules\weex-toolkit\node_modules\babel-core\lib\transformation\file\options\
option-manager.js:224:36)
    at OptionManager.init (C:\Users\Administrator\AppData\Roaming\npm\node_modul
es\weex-toolkit\node_modules\babel-core\lib\transformation\file\options\option-m
anager.js:338:12)
    at File.initOptions (C:\Users\Administrator\AppData\Roaming\npm\node_modules
\weex-toolkit\node_modules\babel-core\lib\transformation\file\index.js:216:65)
    at new File (C:\Users\Administrator\AppData\Roaming\npm\node_modules\weex-to
olkit\node_modules\babel-core\lib\transformation\file\index.js:137:24)
    at Pipeline.transform (C:\Users\Administrator\AppData\Roaming\npm\node_modul
es\weex-toolkit\node_modules\babel-core\lib\transformation\pipeline.js:46:16)
    at transpile (C:\Users\Administrator\AppData\Roaming\npm\node_modules\weex-t
oolkit\node_modules\babel-loader\index.js:38:20)
    at Object.module.exports (C:\Users\Administrator\AppData\Roaming\npm\node_mo
dules\weex-toolkit\node_modules\babel-loader\index.js:131:12)
ERR! ReferenceError: Unknown plugin "C:\Users\Administrator\AppData\Roaming\
\npm\node_modules\weex-toolkit\node_modules\weex-loader\node_modules\babel
-plugin-transform-runtime" specified in "base" at 0, attempted to resolve relati
ve to "E:\weexs\toolbox-weex-master\src"

E:\weexs\toolbox-weex-master\src>

**Comment by hugojing** [comment]
试试先 `npm i` 一下

**Comment by wangGuangXu** [comment]
npm i 是什么意思？  执行后显示：

Microsoft Windows [版本 6.1.7601]
版权所有 (c) 2009 Microsoft Corporation。保留所有权利。

C:\Users\Administrator>cd /d http://localhost:8080/index.html?page=./dist/transl
ate.js
文件名、目录名或卷标语法不正确。

C:\Users\Administrator>npm run serve
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\
node_modules\npm\bin\npm-cli.js" "run" "serve"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! path C:\Users\Administrator\package.json
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\Administrator\
package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Administrator\npm-debug.log

C:\Users\Administrator>cd /d E:\weexs\toolbox-weex-master\src

E:\weexs\toolbox-weex-master\src>weex translate.we --qr
ERR! ModuleBuildError: Module build failed: ReferenceError: Unknown plugin "C:\
Users\Administrator\AppData\Roaming\npm\node_modules\weex-toolkit\node_mo
dules\weex-loader\node_modules\babel-plugin-transform-runtime" specified in "
base" at 0, attempted to resolve relative to "E:\weexs\toolbox-weex-master\sr
c"
    at C:\Users\Administrator\AppData\Roaming\npm\node_modules\weex-toolkit\node
_modules\babel-core\lib\transformation\file\options\option-manager.js:172:17
    at Array.map (native)
    at Function.normalisePlugins (C:\Users\Administrator\AppData\Roaming\npm\nod
e_modules\weex-toolkit\node_modules\babel-core\lib\transformation\file\options\o
ption-manager.js:150:20)
    at OptionManager.mergeOptions (C:\Users\Administrator\AppData\Roaming\npm\no
de_modules\weex-toolkit\node_modules\babel-core\lib\transformation\file\options\
option-manager.js:224:36)
    at OptionManager.init (C:\Users\Administrator\AppData\Roaming\npm\node_modul
es\weex-toolkit\node_modules\babel-core\lib\transformation\file\options\option-m
anager.js:338:12)
    at File.initOptions (C:\Users\Administrator\AppData\Roaming\npm\node_modules
\weex-toolkit\node_modules\babel-core\lib\transformation\file\index.js:216:65)
    at new File (C:\Users\Administrator\AppData\Roaming\npm\node_modules\weex-to
olkit\node_modules\babel-core\lib\transformation\file\index.js:137:24)
    at Pipeline.transform (C:\Users\Administrator\AppData\Roaming\npm\node_modul
es\weex-toolkit\node_modules\babel-core\lib\transformation\pipeline.js:46:16)
    at transpile (C:\Users\Administrator\AppData\Roaming\npm\node_modules\weex-t
oolkit\node_modules\babel-loader\index.js:38:20)
    at Object.module.exports (C:\Users\Administrator\AppData\Roaming\npm\node_mo
dules\weex-toolkit\node_modules\babel-loader\index.js:131:12)
ERR! ReferenceError: Unknown plugin "C:\Users\Administrator\AppData\Roaming\
\npm\node_modules\weex-toolkit\node_modules\weex-loader\node_modules\babel
-plugin-transform-runtime" specified in "base" at 0, attempted to resolve relati
ve to "E:\weexs\toolbox-weex-master\src"

E:\weexs\toolbox-weex-master\src>weex translate.we --qr
ERR! ModuleBuildError: Module build failed: ReferenceError: Unknown plugin "C:\
Users\Administrator\AppData\Roaming\npm\node_modules\weex-toolkit\node_mo
dules\weex-loader\node_modules\babel-plugin-transform-runtime" specified in "
base" at 0, attempted to resolve relative to "E:\weexs\toolbox-weex-master\sr
c"
    at C:\Users\Administrator\AppData\Roaming\npm\node_modules\weex-toolkit\node
_modules\babel-core\lib\transformation\file\options\option-manager.js:172:17
    at Array.map (native)
    at Function.normalisePlugins (C:\Users\Administrator\AppData\Roaming\npm\nod
e_modules\weex-toolkit\node_modules\babel-core\lib\transformation\file\options\o
ption-manager.js:150:20)
    at OptionManager.mergeOptions (C:\Users\Administrator\AppData\Roaming\npm\no
de_modules\weex-toolkit\node_modules\babel-core\lib\transformation\file\options\
option-manager.js:224:36)
    at OptionManager.init (C:\Users\Administrator\AppData\Roaming\npm\node_modul
es\weex-toolkit\node_modules\babel-core\lib\transformation\file\options\option-m
anager.js:338:12)
    at File.initOptions (C:\Users\Administrator\AppData\Roaming\npm\node_modules
\weex-toolkit\node_modules\babel-core\lib\transformation\file\index.js:216:65)
    at new File (C:\Users\Administrator\AppData\Roaming\npm\node_modules\weex-to
olkit\node_modules\babel-core\lib\transformation\file\index.js:137:24)
    at Pipeline.transform (C:\Users\Administrator\AppData\Roaming\npm\node_modul
es\weex-toolkit\node_modules\babel-core\lib\transformation\pipeline.js:46:16)
    at transpile (C:\Users\Administrator\AppData\Roaming\npm\node_modules\weex-t
oolkit\node_modules\babel-loader\index.js:38:20)
    at Object.module.exports (C:\Users\Administrator\AppData\Roaming\npm\node_mo
dules\weex-toolkit\node_modules\babel-loader\index.js:131:12)
ERR! ReferenceError: Unknown plugin "C:\Users\Administrator\AppData\Roaming\
\npm\node_modules\weex-toolkit\node_modules\weex-loader\node_modules\babel
-plugin-transform-runtime" specified in "base" at 0, attempted to resolve relati
ve to "E:\weexs\toolbox-weex-master\src"

E:\weexs\toolbox-weex-master\src>npm install babel-plugin-transform-runtime
npm WARN package.json toolbox-weex@1.0.0 No repository field.
babel-plugin-transform-runtime@6.15.0 ..\node_modules\babel-plugin-transform-run
time
└── babel-runtime@6.11.6 (regenerator-runtime@0.9.5, core-js@2.4.1)

E:\weexs\toolbox-weex-master\src>weex main.we
ERR! ModuleBuildError: Module build failed: ReferenceError: Unknown plugin "C:\
Users\Administrator\AppData\Roaming\npm\node_modules\weex-toolkit\node_mo
dules\weex-loader\node_modules\babel-plugin-transform-runtime" specified in "
base" at 0, attempted to resolve relative to "E:\weexs\toolbox-weex-master\sr
c"
    at C:\Users\Administrator\AppData\Roaming\npm\node_modules\weex-toolkit\node
_modules\babel-core\lib\transformation\file\options\option-manager.js:172:17
    at Array.map (native)
    at Function.normalisePlugins (C:\Users\Administrator\AppData\Roaming\npm\nod
e_modules\weex-toolkit\node_modules\babel-core\lib\transformation\file\options\o
ption-manager.js:150:20)
    at OptionManager.mergeOptions (C:\Users\Administrator\AppData\Roaming\npm\no
de_modules\weex-toolkit\node_modules\babel-core\lib\transformation\file\options\
option-manager.js:224:36)
    at OptionManager.init (C:\Users\Administrator\AppData\Roaming\npm\node_modul
es\weex-toolkit\node_modules\babel-core\lib\transformation\file\options\option-m
anager.js:338:12)
    at File.initOptions (C:\Users\Administrator\AppData\Roaming\npm\node_modules
\weex-toolkit\node_modules\babel-core\lib\transformation\file\index.js:216:65)
    at new File (C:\Users\Administrator\AppData\Roaming\npm\node_modules\weex-to
olkit\node_modules\babel-core\lib\transformation\file\index.js:137:24)
    at Pipeline.transform (C:\Users\Administrator\AppData\Roaming\npm\node_modul
es\weex-toolkit\node_modules\babel-core\lib\transformation\pipeline.js:46:16)
    at transpile (C:\Users\Administrator\AppData\Roaming\npm\node_modules\weex-t
oolkit\node_modules\babel-loader\index.js:38:20)
    at Object.module.exports (C:\Users\Administrator\AppData\Roaming\npm\node_mo
dules\weex-toolkit\node_modules\babel-loader\index.js:131:12)
ERR! ReferenceError: Unknown plugin "C:\Users\Administrator\AppData\Roaming\
\npm\node_modules\weex-toolkit\node_modules\weex-loader\node_modules\babel
-plugin-transform-runtime" specified in "base" at 0, attempted to resolve relati
ve to "E:\weexs\toolbox-weex-master\src"

E:\weexs\toolbox-weex-master\src>npm -i

Usage: npm <command>

where <command> is one of:
    access, add-user, adduser, apihelp, author, bin, bugs, c,
    cache, completion, config, ddp, dedupe, deprecate, dist-tag,
    dist-tags, docs, edit, explore, faq, find, find-dupes, get,
    help, help-search, home, i, info, init, install, issues, la,
    link, list, ll, ln, login, logout, ls, outdated, owner,
    pack, ping, prefix, prune, publish, r, rb, rebuild, remove,
    repo, restart, rm, root, run-script, s, se, search, set,
    show, shrinkwrap, star, stars, start, stop, t, tag, team,
    test, tst, un, uninstall, unlink, unpublish, unstar, up,
    update, upgrade, v, version, view, whoami

npm <cmd> -h     quick help on <cmd>
npm -l           display full usage info
npm faq          commonly asked questions
npm help <term>  search for help on <term>
npm help npm     involved overview

Specify configs in the ini-formatted file:
    C:\Users\Administrator.npmrc
or on the command line via: npm <command> --key value
Config info can be viewed via: npm help config

npm@2.15.8 C:\Program Files\nodejs\node_modules\npm

E:\weexs\toolbox-weex-master\src>

**Comment by hugojing** [comment]
就是 npm  install

**Comment by wangGuangXu** [comment]
我 npm install 后还是不行：
C:\Users\Administrator>npm install
npm ERR! install Couldn't read dependencies
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\
node_modules\npm\bin\npm-cli.js" "install"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! path C:\Users\Administrator\package.json
npm ERR! code ENOPACKAGEJSON
npm ERR! errno -4058
npm ERR! syscall open

npm ERR! package.json ENOENT: no such file or directory, open 'C:\Users\Administ
rator\package.json'
npm ERR! package.json This is most likely not a problem with npm itself.
npm ERR! package.json npm can't find a package.json file in your current directo
ry.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Administrator\npm-debug.log

C:\Users\Administrator>
是不是我Node.JS或者 npm装的 有问题

**Comment by hugojing** [comment]
在 `E:\weexs\toolbox-weex-master` 下 `npm install`

**Comment by wangGuangXu** [comment]
按照你提示的安装后，运行http://localhost:8080/index.html?page=./dist/translate.js 是可以的，但是切换打src目录下的时候执行weex main.we --qr 命令还是报错：

E:\weexs\toolbox-weex-master\src>weex main.we --qr
ERR! ModuleBuildError: Module build failed: ReferenceError: Unknown plugin "C:\
Users\Administrator\AppData\Roaming\npm\node_modules\weex-toolkit\node_mo
dules\weex-loader\node_modules\babel-plugin-transform-runtime" specified in "
base" at 0, attempted to resolve relative to "E:\weexs\toolbox-weex-master\sr
c"
    at C:\Users\Administrator\AppData\Roaming\npm\node_modules\weex-toolkit\node
_modules\babel-core\lib\transformation\file\options\option-manager.js:172:17
    at Array.map (native)
    at Function.normalisePlugins (C:\Users\Administrator\AppData\Roaming\npm\nod
e_modules\weex-toolkit\node_modules\babel-core\lib\transformation\file\options\o
ption-manager.js:150:20)
    at OptionManager.mergeOptions (C:\Users\Administrator\AppData\Roaming\npm\no
de_modules\weex-toolkit\node_modules\babel-core\lib\transformation\file\options\
option-manager.js:224:36)
    at OptionManager.init (C:\Users\Administrator\AppData\Roaming\npm\node_modul
es\weex-toolkit\node_modules\babel-core\lib\transformation\file\options\option-m
anager.js:338:12)
    at File.initOptions (C:\Users\Administrator\AppData\Roaming\npm\node_modules
\weex-toolkit\node_modules\babel-core\lib\transformation\file\index.js:216:65)
    at new File (C:\Users\Administrator\AppData\Roaming\npm\node_modules\weex-to
olkit\node_modules\babel-core\lib\transformation\file\index.js:137:24)
    at Pipeline.transform (C:\Users\Administrator\AppData\Roaming\npm\node_modul
es\weex-toolkit\node_modules\babel-core\lib\transformation\pipeline.js:46:16)
    at transpile (C:\Users\Administrator\AppData\Roaming\npm\node_modules\weex-t
oolkit\node_modules\babel-loader\index.js:38:20)
    at Object.module.exports (C:\Users\Administrator\AppData\Roaming\npm\node_mo
dules\weex-toolkit\node_modules\babel-loader\index.js:131:12)
ERR! ReferenceError: Unknown plugin "C:\Users\Administrator\AppData\Roaming\
\npm\node_modules\weex-toolkit\node_modules\weex-loader\node_modules\babel
-plugin-transform-runtime" specified in "base" at 0, attempted to resolve relati
ve to "E:\weexs\toolbox-weex-master\src"

E:\weexs\toolbox-weex-master\src>

**Comment by hugojing** [comment]
src 目录下应该没有 main.we 文件

**Comment by wangGuangXu** [comment]
有的，这个是下载您这个示例的src目录。我自己也没摸索出解决办法，还得老麻烦你，实在是给你添麻烦了

**Comment by wangGuangXu** [comment]
还有，我的Node.js是VS开发工具装的时候自带的。是4.4.7的版本，是否和这个由关系

**Comment by wangGuangXu** [comment]
我发现你这个代码，在我笔记本的环境下是跑起来了，在我们公司下就一直报上面的错。

**Comment by wangGuangXu** [comment]
手机扫描后什么都没有这是什么情况

**Comment by hugojing** [comment]
不在同一 wifi 下吧。。
