### ISSUE TITLE
服务器如何下发js给客户端？

### ISSUE THREAD

**Issue by JiongXing** [hugojing/toolbox-weex#12]
你好，请问项目中部分页面使用weex动态渲染的话，js文件不在本地存放。那么we文件编写完成后，应如何解析成js，并下发给客户端？谢谢

**Comment by hugojing** [comment]
简单点就是把 JS 文件构建好，放在静态资源服务器上，客户端加载网络路径就行了。

你要动态下发给客户端，那就给个接口，接口上给出可随时变动的网络路径，拿到路径再加载。

**Comment by JiongXing** [comment]
tks，明白了
