### ISSUE TITLE
提示我vue不匹配？

### ISSUE THREAD

**Issue by liuhuanzhu** [hugojing/toolbox-weex#13]
`$ weex main.we --qr
ERR! [webpack errors]

Vue packages version mismatch:

- vue@1.0.26
- vue-template-compiler@2.1.8

This may cause things to work incorrectly. Make sure to use the same version for
 both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify sho
uld bump vue-template-compiler to the latest.

你好，按照您说的提示，我执行weex main.we --qr 报这个错。没有其他地方指定vue-loader版本。需要在哪配置？谢谢。

`

**Comment by liuhuanzhu** [comment]
找到原因了  还得把之前的全局vue 版本做一下更新才可以。

**Comment by appbeijing** [comment]
不要卸载全局的，卸载项目里的就可以的
