### ISSUE TITLE
input控件发布到手机上输入光标不显示、value绑定问题

### ISSUE THREAD

**Issue by squirrelx** [hugojing/toolbox-weex#2]
1.发布到手机上看，input的输入光标不显示
2.value绑定，比如value={{mytext}},  在data中设置后确实可以展示，但是后面通过别的事件来更改这个mytext，input的值不跟着改变

**Comment by squirrelx** [comment]
<template>
   <div class="top">
     <input type="text" class="input" value="{{mytext}}"></input>
     <text onclick="deletetext">delete</text>
   </div>
</template> 

<style>
   .top {
     flex-direction: column;
     justify-content: center;
 }
</style> 

<script>
 module.exports = {
   data: {
     mytext: 'textneed2delete',
   },
   methods: {
     deletetext: function() {
       //alert("123");
       this.mytext="";
     }
  }
 }
</script>

**Comment by squirrelx** [comment]
<template>
 <div class="top">
 <input type="text" class="input" value="{{mytext}}"></input>
 <text onclick="deletetext">delete</text>
 </div>
</template> 

<style>
 .top {
 flex-direction: column;
 justify-content: center;
 }

</style> 

<script>
 module.exports = {
 data: {
 mytext: 'textneed2delete',
 },
 methods: {
 deletetext: function() {
 //alert("123");
 this.mytext="";
 }
 }
 }
</script>

**Comment by hugojing** [comment]
1. input 控件本就没有自带输入光标；
2. 更改 data.mytext ，value 本来就不改变。因为 input 的 value 只能被输入事件（onchange、oninput）改变，而不能被 mytext 的改变而改变。value={{mytext}} 只是设置一个初始的值，完全可以不用。

**Comment by squirrelx** [comment]
1.input控件没有输入光标应该是当前功能不支持，任何一个手机app的输入框基本都有输入光标的
2.既然采用了数据绑定{{}} 就应该联动显示，angularjs就可以，这个已经反馈给github  他们说是bug  后续release版本会修复（输入框后面加个删除按钮，用于清除输入的内容，这个场景太常见了）

**Comment by hugojing** [comment]
太好了
