### ISSUE TITLE
在weexPlayGround打开，点击底部的item都是跳转成扫码页面的？

### ISSUE THREAD

**Issue by YoringChen** [hugojing/toolbox-weex#3]
this.$openURL这个方法是用来跳转页面的吧，为什么在例子是跳转成扫码？

另外this.$openURL在官方文档哪里有提及到，都找不到 T T，而且也不知道里面的url结构是怎么回事。

谢谢

**Comment by hugojing** [comment]
this.$openURL 的确是页面跳转。

例子中，是 Web 平台上的页面跳转，在 playground 上无法正常跳转，因为在 iOS / Android 平台上的路径不对。（三平台的路径目前需要自行 hack）

建议试试 http://alibaba.github.io/weex/doc/components/a.html ，看能不能满足你的需求。
