### ISSUE TITLE
为什么require('@weex-module/stream')仍然报找不到module

### ISSUE THREAD

**Issue by catliuqh** [hugojing/toolbox-weex#4]
```
var stream = require('@weex-module/stream');
function getData(url, callback) {
    stream.fetch({
        method: 'GET',
        url: url,
        type:'jsonp'
    }, function (ret) {
        var retdata = JSON.parse(ret);
        callback(retdata);
    });
}
```

这段代码我在运行的时候报找不到模块weex-module/stream
为什么会引入不成功，怎么解决这个问题

**Comment by hugojing** [comment]
你这段代码在 js 文件还是 we 文件中？

**Comment by catliuqh** [comment]
在js文件，我换了下面这种写法就可以了，但是为什么这样引入报找不到模块
var stream
**weex_define**('@weex-temp/x', function (**weex_require**) {
  stream = **weex_require**('@weex-module/stream')
})

**Comment by hugojing** [comment]
因为目前 js 文件下暂不能直接引入 @weex-module， 只能通过 weex_define(x, callback) 的临时方式来引入和使用。
