### ISSUE TITLE
翻译异常

### ISSUE THREAD

**Issue by williamLu1981** [hugojing/toolbox-weex#5]
一直报 ‘网络通信失败，请确认网络状况’,
我确认网络正常，如果直接在浏览器中访问提交的地址，可以拿到返回的JSON值。

XMLHttpRequest cannot load https://fanyi.youdao.com/openapi.do?keyfrom=min-toolbox&key=1267180728&type=data&doctype=json&version=1.1&q=apple. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access.
应该是跨域问题。

**Comment by hugojing** [comment]
嗯，浏览器限制了你的跨域请求。

**Comment by williamLu1981** [comment]
怎么解决？

**Comment by hugojing** [comment]
1. 自己造一个不遵守跨域限制准则的浏览器。
2. 把现有的浏览器改成不作限制的。
3. 做个服务器，在服务器端请求数据并返回给自己的网页。
4. 终极方式：不做网页，做 native 客户端。

**Comment by JakeWoki** [comment]
怎么把现有的浏览器改成不作限制的呢？我用的是谷歌浏览器

**Comment by hugojing** [comment]
@JakeWoki 我用的是一个叫 CORS Toggle 的浏览器插件
