### ISSUE TITLE
为什么Weex-loader-0.3.1还是不支持在 js 中 require('@weex-module/stream');

### ISSUE THREAD

**Issue by resse92** [hugojing/toolbox-weex#7]
![image](https://cloud.githubusercontent.com/assets/14215749/18436748/7cea2f2c-792c-11e6-9b38-686587be6b74.png)

**Comment by hugojing** [comment]
不清楚。建议继续使用临时黑魔法引入 Weex module

**Comment by AggerChen** [comment]
楼主能否讲讲这个临时黑魔法是怎么个原理？
`var modal__weex_define__('@weex-temp/x', function (__weex_require__) {
  modal = __weex_require__('@weex-module/modal')
})`

**Comment by hugojing** [comment]
@AggerChen 

```
__weex_define__('@weex-temp/x', function (__weex_require__) {
  modal = __weex_require__('@weex-module/modal')
})
```

这要什么原理。。。。难道不是 Weex  提供的一个 `__weex_define__(xx, callback)` 方法？
